name: RotatingHeads2
author: Gennario
version: 1.1.1
main: cz.gennario.newrotatingheads.Main
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Multiworld
  - Multiverse-Core
  - TransparentHeads
depend:
  - ProtocolLib
